### ISSUE TITLE
Additional Mask for Bed state (prison/guest/medical)

### ISSUE THREAD

**Issue by BaalEvan** [emipa606/SdGoodnight#1]
Hey!

Could you add Green Layer to bedMasks for blanket, because right now there is no way to see which bed is Guest/Prison/Medical and which is a normal one. Example from VanillaTexturesExpanded (red is material, green is "state")
![Bed_eastm](https://user-images.githubusercontent.com/1843494/92421404-a849cd80-f178-11ea-85dd-8a45ef47505b.png)

**Comment by BaalEvan** [comment]
example based on current textures :P 
![image](https://user-images.githubusercontent.com/1843494/92421470-ecd56900-f178-11ea-9b84-2816ed277d56.png)

**Comment by emipa606** [comment]
Should be done now, thanks for the suggestion!
